import "@/app/globals.css";

export const metadata = {
    title: "Contact Us",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html>
            <body>
                {children}
            </body>
        </html>
    );
}
